### ISSUE TITLE
charter template links are broken

### ISSUE THREAD

**Issue by baskaufs** [tdwg/website#115]
**Page(s) where issue occurs**
Community management

> Your url(s) here
https://www.tdwg.org/community/management/

**Issue description**
The links for the Interest and Task Group charters are broken.  I did not check whether other links were broken

> What is wrong? What were you expecting instead?
Expected to be able to download the charter templates.

**Comment by baskaufs** [comment]
The templates seem to be here:
https://rs.tdwg.org/documents/templates/
although my browser was complaining about security issues

**Comment by stanblum** [comment]
I don't know what lead you search for them on the rs.tdwg.org (which seems to be http instead of https), but thanks for the reminder.  The better URLs for those are https://static.tdwg.org/documents/...  Those corrections are now updated on page in the first comment.  Actually, these docs need to be reviewed, updated as necessary, converted to markdown and re-posted.  I'm going to remove the links to the powerpoint templates for 5 min presentations at business meeting.
