### ISSUE TITLE
Adding new task group of the TAG; can't make "Technical Architecture Group" show as an IG on the Community page.

### ISSUE THREAD

**Issue by stanblum** [tdwg/website#540]
**Page(s) where issue occurs**

/community/index.md  https://github.com/tdwg/website/blob/master/community/index.md

**Issue description**

A few weeks ago, the Exec approved the charter for the Standards Mapping Task Group, which is authorized under the TAG.  Of course the TAG was changed from an "interest group analog" to a "functional subcommittee" under the most recent Constitution, but everyone agrees that the best place to hang this new task group is the TAG.  The problem is:  how to get it listed on our Community page?  My "simplest solution" was to follow the model of other interest groups and add to the list; using `label IG` but to use the TAG URL as the href value (i.e., without moving the TAG page), and also add its one task group to the list, giving its labe and href. You can see at the bottom of list (code in header) for the Community page, and then at the bottom of the rendered page itself.  My supposition was that your page rendering process would read the title from the TAG page (found as the URL target /about/committees/tag/), and insert that title in the list.  But it doesn't render -- nothing shows where "Technical Architecture Group" should appear.  The key difference, obviously, is that the TAG page is not under Community.  Is that the key restriction, or is the controlling content somewhere else?

I placed the standards-mapping task group page underneath the TAG page
`/about/committees/tag/standards-mapping/` 

Note also, that I followed the model for the other IG pages, and added some lines to the header of the TAG page
/about/committees/tag/index.md
At the top: 
`layout: list `
and at the bottom of the header
```
list:
- label: TG
  href: /community/standards-mapping/
```
 And then at the bottom of the TAG page, I inserted the Task Groups as heading-2 followed by the comment:
```
## Task groups

<!-- list will be inserted below content -->
```

Is the solution to move the TAG page (and subpages) from /about/committees/  to /community/  ?

**Comment by peterdesmet** [comment]
Hi Stan, you did all of it correctly, except that the TAG page URL in the community list was missing a trailing slash. This results in the code looking for the non-existent https://www.tdwg.org/about/committees/tag.html rather than https://www.tdwg.org/about/committees/tag/ and therefore not finding a title. I fixed this in https://github.com/tdwg/website/commit/15275264c5c34f57cfa39165b69d6e44b8f4b570.

- https://www.tdwg.org/community/#interest-and-task-groups now shows the title for TAG
- You did the right thing for the TAG page itself. By adding `layout: list` and including the child page, it is now shown on that page at the bottom. Good that you added the `## Task groups` header too. The comment is not required, but just useful for other editors.

**Comment by stanblum** [comment]
Thanks, Peter!
